gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: 604800
    cookie:
        enabled: true
        same_site: strict
        domain: '.%env(resolve:DOMAIN)%'
        http_only: true
        secure: false
        remove_token_from_body: true
