lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600

    token_extractors:
        split_cookie:
            enabled: true
            cookies:
                - jwt_hp
                - jwt_s

    set_cookies:
        jwt_hp:
            samesite: strict
            httpOnly: false
            secure: false
            domain: '.%env(resolve:DOMAIN)%'
            split:
                - header
                - payload

        jwt_s:
            lifetime: 0
            samesite: strict
            domain: '.%env(resolve:DOMAIN)%'
            httpOnly: true
            secure: false
            split:
                - signature