nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'access-control-expose-headers', 'Authorization', 'apollographql-client-name', 'apollographql-client-version', 'batch', 'Cookie']
        expose_headers: ['Link', 'Cache-Control', 'Content-Language', 'Content-Type', 'Content-Disposition', 'Expires', 'Last-Modified', 'Pragma', 'Set-Cookie']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/': null
