when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
#       https://docs.sentry.io/platforms/php/guides/symfony/#monolog-integration
        register_error_listener: false
        options:
            send_default_pii: true
