twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_domain: '%env(APP_DOMAIN)%'
        http_scheme: '%env(HTTP_SCHEME)%'

when@test:
    twig:
        strict_variables: true
